### ISSUE TITLE
Language selection does not work on macOS 10.10 Yosemite

### ISSUE THREAD

**Issue by snomos** [divvun/ckeditor-plugin-giella-scayt#2]
According to e-mail report from PC Biti. No browsers seem to work on this OS. Needs further investigation.

**Comment by albbas** [comment]
Could it be that port 3000 is closed? Does other machines on the same net, but another OS version work?

**Comment by snomos** [comment]
Your analysis is correct. This is the latest info I got via email:

> Jeg har sett litt mer på dette og det har ikke noe med mac os å gjøre. Det er et brannmur problem på noen av våre kontorer. Vi får ikke opp spellingen i Karasjok og Kauto, men i Alta kommer den opp. Spellingen går tydeligvis igjennom noen porter som er steng fra vår brannvegg.

So this is not related to the OS, or our code at all. i close this bug report.
